# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = true
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["lib"]
  optimizer = false
  optimizer_runs = 5_000
  out = "out"
  script = "script"
  src = "src"
  test = "test"
  libraries = ["lib/contracts/contracts/lib/Poseidon.sol:PoseidonUnit2L:0x8710AF1E1fbb7CD000B2fBd85b5597B23B0E22d5",
  "lib/contracts/contracts/lib/Poseidon.sol:PoseidonUnit3L:0x30dcb60E5D5778D70992705a7Ff51ce2b85dAB5b",
  "lib/contracts/contracts/lib/Poseidon.sol:PoseidonUnit4L:0xCa98B4CA0F7858dF9b5C11B11e85A6E3269ED5ca",
  "lib/contracts/contracts/lib/IdentityLib.sol:IdentityLib:0xD679c90A27D09E3A76e99d8e705079F1a281537b",
  "lib/contracts/contracts/lib/SmtLib.sol:SmtLib:0x095a4304859A3B6beD68CDb1d112690715C29596"]

[profile.functions]
  solc_version = '0.8.19'
  src = 'lib/chainlink/contracts/src/v0.8/functions/'
  gas_price = 4000000000
  out = 'out'

[profile.identity]
  solc_version = '0.8.16'
  src = 'lib/contracts/contracts/'


[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  amoy = { key = "${API_KEY_POLYGONSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  amoy = "https://polygon-amoy.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
